# Generated by Django 4.0.4 on 2022-05-05 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_subscriber_subscriptions_topic_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email_id',
            field=models.CharField(max_length=100),
        ),
    ]
