# Generated by Django 4.0.4 on 2022-05-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_topic_options_remove_topic_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.topic'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.topic'),
        ),
    ]
