# Generated by Django 3.2.13 on 2022-05-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_article_topic_alter_subscriber_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='notification_time',
        ),
        migrations.AddField(
            model_name='article',
            name='hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
